# Generated by Django 2.1.1 on 2019-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BFM_Parse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfm_rs_file', models.FileField(upload_to='')),
            ],
        ),
    ]
