# Generated by Django 2.1.1 on 2019-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseBFM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendbfm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfm_rq_file', models.FileField(upload_to='')),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
