# Generated by Django 2.1.1 on 2019-02-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseBFM', '0002_sendbfm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendbfm',
            name='token',
            field=models.CharField(max_length=300),
        ),
    ]
