# Generated by Django 2.1.1 on 2019-02-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parseBFM', '0003_auto_20190219_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendbfm',
            name='parsebfm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parseBFM.BFM_Parse'),
            preserve_default=False,
        ),
    ]
