# Generated by Django 2.1.1 on 2019-02-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parseBFM', '0004_sendbfm_parsebfm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendbfm',
            name='parsebfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parseBFM.BFM_Parse'),
        ),
    ]
