# Generated by Django 2.1.1 on 2019-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseBFM', '0006_bfm_parse_bfm_rs_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bfm_parse',
            name='bfm_rs_file',
            field=models.FileField(upload_to='static/folder/'),
        ),
    ]
